package com.multicar.repository.demo.enums;

public enum Permission {
    USER_MANAGEMENT,
    ROLE_MANAGEMENT,
    PERMISSION_MANAGEMENT,
    COMPANY_MANAGEMENT,
    INVENTORY_MANAGEMENT,
    JOB_CARD_MANAGEMENT,
    INVOICE_MANAGEMENT,
    SUPPLIER_MANAGEMENT,
    PURCHASE_ORDER_MANAGEMENT,
    VIEW_DASHBOARD
}







